[features]
seeds = true
skip-lint = false

[toolchain]
anchor_version = "0.32.1"

[programs.localnet]
lime_market = "G2YAvLwHFmd4wgs45QScmBYpFthkEjhU34VKQ3HKMagk"
lime_vault = "BY7MggeDqzyGgJnCQ34pF5pJA6kGUtNvFhaW4VHbFnLm"
lime_settlement = "5gchRUqZFCFKWrp1oUdWih6SavGdYoSrZuGwB6bz4hKB"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npm run test:anchor"
